[workspace]
members = ["hmac-sha256-circuits", "hmac-sha256"]
resolver = "2"

[workspace.dependencies]
# tlsn
mpz-circuits = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "1f2c922" }
mpz-garble = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "1f2c922" }

# async
async-trait = "0.1"
futures = "0.3"
tokio = "1"

# error/log
thiserror = "1"
tracing = "0.1"

# testing
criterion = "0.5"

[patch.'https://github.com/privacy-scaling-explorations/mpz']
mpz-circuits = { path = "../../../mpz/mpz-circuits" }
mpz-garble = { path = "../../../mpz/garble/mpz-garble" }