[package]
name = "tlsn-universal-hash"
version = "0.1.0"
edition = "2021"

[features]
default = ["ghash", "mock"]
tracing = ["dep:tracing"]
ghash = []
mock = []

[dependencies]
# tlsn
tlsn-mpc-core = { path = "../mpc/mpc-core" }
tlsn-mpc-share-conversion-core = { path = "../mpc/share-conversion/mpc-share-conversion-core" }
tlsn-mpc-share-conversion = { path = "../mpc/share-conversion/mpc-share-conversion" }

# async
async-trait = "0.1"
futures = "0.3"
futures-util = "0.3"

# error/log
thiserror = "1"

# misc
derive_builder = "0.12"
tracing = {version = "0.1", optional = true}

[dev-dependencies]
ghash_rc = { package = "ghash", version = "0.5" }
tokio = "1"
criterion = "0.5"
rstest = "0.17"
rand_chacha = "0.3"
rand = "0.8"
generic-array = "0.14"

