[package]
name = "actor-ot"
authors = ["TLSNotary Team"]
description = "A wrapper crate for Oblivious Transfer protocols"
keywords = ["tls", "mpc", "2pc", "ot"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpz-ot-core = { git = "https://github.com/tlsnotary/mpz", rev = "86f1687" }
mpz-ot = { git = "https://github.com/tlsnotary/mpz", rev = "86f1687" }
mpz-core = { git = "https://github.com/tlsnotary/mpz", rev = "86f1687" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils" }
async-trait = "0.1"
derive_builder = "0.11"
futures = "0.3"
thiserror = "1"
xtra = { git = "https://github.com/Restioson/xtra", rev = "ca061b4", features = [
    "macros",
], default-features = false }

[features]
default = ["mock"]
mock = []


[dev-dependencies]
xtra = { git = "https://github.com/Restioson/xtra", rev = "ca061b4", features = [
    "tokio",
], default-features = false }
tokio = { version = "1.23", features = [
    "macros",
    "rt",
    "rt-multi-thread",
] }
