server:
  name: "notary-server"
  host: "0.0.0.0"
  port: 7047

notarization:
  max-transcript-size: 65536

tls:
  enabled: false
  private-key-pem-path: "/data/privkey.pem"
  certificate-pem-path: "/data/cert.pem"

notary-signature:
  private-key-pem-path: "./fixture/notary/notary.key"
  public-key-pem-path: "./fixture/notary/notary.pub"

tracing:
  default-level: DEBUG

authorization:
  enabled: false
  whitelist-csv-path: "./fixture/auth/whitelist.csv"
