name: Rust

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build_and_test:
    if: ( ! github.event.pull_request.draft )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - integration-tests
          - uid-mux
          - actors/actor-ot
          - cipher
          - universal-hash
          - aead
          - key-exchange
          - point-addition
          - prf
          - tls
        include:
          - package: integration-tests
            release: true
    defaults:
      run:
        working-directory:  ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3


      - name: Nightly with rustfmt
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: "Check formatting"
        run: cargo +nightly fmt --check --all

      - name: Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.0.0

      - name: "Build"
        run: cargo build ${{ matrix.release && '--release' }}

      - name: "Test"
        if: ${{ matrix.release != true }}
        run: cargo test --lib --bins --tests --examples --workspace

      - name: "Integration Test"
        if: ${{ matrix.release == true }}
        run: cargo test --release --tests
